plugins {
    id 'java'
    id 'org.springframework.boot' version "${spring_boot}"
    id 'io.spring.dependency-management' version "${dependency_plugin}"
}

group = "${group_name}"
version = "${app_version}"

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}
subprojects {
    apply plugin: 'io.spring.dependency-management'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${spring_boot}"
        }
    }
}

dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:${spring_boot}")

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation project(':oracle-buffered-logger')

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${swagger}"
    runtimeOnly 'com.oracle.database.jdbc:ojdbc11'
}

tasks.named('test') {
    useJUnitPlatform()
}

springBoot  {
    buildInfo()
}

bootJar {
    enabled = true
}
