group_name=com.jiocoders
app_version=0.0.1-SNAPSHOT
spring_boot=3.5.8
dependency_plugin=1.1.7
swagger=2.8.13
lombok=1.18.30

###################################################
#Local#./gradlew publishToMavenLocal
#Github#./gradlew :oracle-buffered-logger:publish
#Maven#./gradlew publishMavenPublicationToCentralPortal

#Sending key
# 1. Send to Ubuntu (Primary)
#gpg --keyserver keyserver.ubuntu.com --send-keys 28B36364
# 2. Send to OpenPGP (Backup)
#gpg --keyserver keys.openpgp.org --send-keys 28B36364
# 3. Send to MIT (Backup)
#gpg --keyserver pgp.mit.edu --send-keys 28B36364
#harry@Harrys-MacBook-Air ~ % gpg --batch --passphrase "Jiocoders@321" --quick-gen-key "Jiocoders <Jiocoders@gmail.com>" default default never
#gpg: directory '/Users/harry/.gnupg/openpgp-revocs.d' created
#gpg: revocation certificate stored as '/Users/harry/.gnupg/openpgp-revocs.d/8845F62B0E3CAC681221DD85B617546A28B36364.rev'
#harry@Harrys-MacBook-Air ~ % gpg --armor --export-secret-keys 28B36364 > private-key.txt
## GPG Key configuration for signing artifacts
## (Use 'gpg --list-keys' to get your key ID)

# Maven configurations
mavenCentralPublishing=true
signAllPublications=true
mavenCentralAutomaticPublishing=true
android.defaults.buildfeatures.publishing=true

GROUP=com.jiocoders
POM_ARTIFACT_ID=log-utils
VERSION_NAME=0.0.2

# GPG signing
#signing.gnupg.keyName=28B36364
#signing.gnupg.passphrase=Jiocoders@321
#signing.secretKeyRingFile=/home/user/.gnupg/secring.gpg
#signing.secretKeyRingFile=-----BEGIN PGP PRIVATE KEY BLOCK-----<your full key here>-----END PGP PRIVATE KEY BLOCK-----

# Add this line (replace with your exact output path from Step 1)
signing.gnupg.executable=/opt/homebrew/bin/gpg
###################################################
#gpg --export-secret-keys -o ~/.gnupg/secring.gpg
