# Oracle Database Connection Properties
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: JIODB
    password: Password123
    driver-class-name: oracle.jdbc.OracleDriver

  # JPA/Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        jdbc:
          batch_size: 50
        order_inserts: true

# Thread Pool Configuration
event:
  threadPool:
    size:
      core: 5
      max: 10
      batch: 800
  flush:
    interval-ms: 500000
